content:
  - name: posts
    label: Posts
    path: _posts
    type: collection
    view:
      fields: [ title, date, category, tags, published ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: category
        label: Category
        type: string
        list: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: published
        label: Published
        type: boolean
      - name: body
        label: Body
        type: rich-text