backend:
  name: github
  repo: hongping/hongping.github.io # Path to your GitHub repository
  branch: main
  base_url: https://sveltia-cms-auth.hong-ping-tan.workers.dev  
media_folder: "assets/img"
collections:
  # Blog posts
  - name: 'posts'
    label: 'Posts'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: 'short_name',
        }
      - { label: 'Categories', name: 'categories', widget: 'list', required: false } # Add categories field
      - { label: 'Tags', name: 'tags', widget: 'list', required: false } # Add tags field (as a list)
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }  
